### PR TITLE
RM-7391: BinariesProvider of Chrome, Edge & Firefox should throw a comprehensive exception when an error occurs while downloading the driver

### PR DESCRIPTION
**Pull request by iam-mholle**
https://re-motion.atlassian.net/browse/RM-7391

### CODE REVIEW

**Comment by iam-mholle** [comment]
@MichaelKetting The binary providers for Chrome and Edge currently only handle 404 `WebException`'s. I guess this should be extended to also include a comprehensive exception on non-404's?

**Comment by MichaelKetting** [comment]
> 
> 
> @MichaelKetting The binary providers for Chrome and Edge currently only handle 404 `WebException`'s. I guess this should be extended to also include a comprehensive exception on non-404's?

yeah, probably helpful to just ahdnle all WebExceptions. there's a hihger proabability that any exception will be some sort of transient web error and we still get statuscode and original message anyway. so telling the developer (i.e. us) that this is just a server side fuck up and don't worry, just use a towel to snap-hit the servers restart button is likely more often correct than wrong.

**Comment by iam-mholle** [comment]
> yeah, probably helpful to just ahdnle all WebExceptions.

@MichaelKetting Should those be a separate issue?

**Comment by MichaelKetting** [comment]
> 
> 
> > yeah, probably helpful to just ahdnle all WebExceptions.
> 
> @MichaelKetting Should those be a separate issue?
@iam-mholle 
depends. is it cheap to do this right now and works in the basic scope of the original issue or is it somehting totally unrelated?

**Comment by iam-mholle** [comment]
@MichaelKetting Could be done cheap. I'll adapt the issue and update this PR.

**Comment by iam-mholle** [comment]
Added to master with f3d2480ea500a94aa94d1da820069bccf3a36829.

**Pull request closed without merging**
