### PR TITLE
RM-7449: RetryAttribute should be added to BinariesProvider tests of Firefox, Chrome & Edge

### PR DESCRIPTION
**Pull request by iam-mholle**
https://re-motion.atlassian.net/browse/RM-7449

### CODE REVIEW

**Comment by iam-mholle** [comment]
This could still prevent build failures due to one failing request, which could be related to many things.

**Comment by MichaelKetting** [comment]
> 
> 
> > This is fine, but I would like to voice my doubts if that does anything. In my head, if Github is down now, it'll be down in 3 seconds as well, but if it's just a network failure that works the next time, that is fine
> 
> This could still prevent build failures due to one failing request, which could be related to many things.

Regarding how long Github is down. We don't know why Github is unreachable in the middle of our night and how long that remains the case. It might just be a one-off network problem that's fixed with the next call. We don't know yet.

**Comment by MichaelKetting** [comment]
It would be really great to get a retry-attribute that accepts a delay. maybe a feature request to nunit?

**Comment by Stefan-Ilic** [comment]
> 
> 
> It would be really great to get a retry-attribute that accepts a delay. maybe a feature request to nunit?

We'd probably be better off to make one ourselves, the wait time for NUnit to implement that would probably be too long anyway

**Comment by MichaelKetting** [comment]
> 
> 
> > It would be really great to get a retry-attribute that accepts a delay. maybe a feature request to nunit?
> 
> We'd probably be better off to make one ourselves, the wait time for NUnit to implement that would probably be too long anyway

Well, then, do we have a ticket for this?

**Comment by iam-mholle** [comment]
> 
> 
> > > It would be really great to get a retry-attribute that accepts a delay. maybe a feature request to nunit?
> > 
> > 
> > We'd probably be better off to make one ourselves, the wait time for NUnit to implement that would probably be too long anyway
> 
> Well, then, do we have a ticket for this?

https://re-motion.atlassian.net/browse/RM-7450

**Comment by iam-mholle** [comment]
Added to master with 3d85cc22b633b65e641155507145e601ca6dbea9.

**Pull request closed without merging**
